### ISSUE TITLE
Update Supermarket with latest version

### ISSUE THREAD

**Issue by Padgett** [smarkets/chef-raspberry-pi#2]
Supermarket (https://supermarket.chef.io/cookbooks/raspberry-pi) only has v0.1.0, source shows v0.1.1 as current.

**Comment by alexdias** [comment]
Hey Joshua, thanks for the heads up. I'll try to get @russss to update it.

**Comment by russss** [comment]
That's now done, sorry for the delay.

**Comment by Padgett** [comment]
:thumbsup:
